services:
  middleware:
    build: "./middleware"
    ports:
      - "8000:8000"
    env_file:
      - ./middleware/.env
  audio:
    build: "model_audio"
    ports:
      - "8001:8001"
    env_file:
      - ./model_audio/.env
  text:
    build: "model_text"
    ports:
      - "8002:8002"
    env_file:
      - ./model_text/.env
  video:
    build: "model_video"
    ports:
      - "8003:8003"
    env_file:
      - ./model_video/.env
  
networks:
  default:
