services:
  middleware:
    build: "./middleware"
    ports:
      - "8000:8000"
  audio:
    build: "model_audio"
    ports:
      - "8001:8001"
  text:
    build: "model_text"
    ports:
      - "8002:8002"
  video:
    build: "model_video"
    ports:
      - "8003:8003"
